### PR TITLE
Some fixes that get builds working under Fedora

### PR DESCRIPTION
**Pull request by portante**

### CODE REVIEW

**Comment by portante** [comment]
This set of patches just tries to get an RPM to build.  I have not installed it to see if things work yet.  Sorry.

I plan on building another package set based on this to do that, since I need a few 8.16 targeted patches for my environment.

**Comment by portante** [comment]
I was able to get the Fedora proper rsyslog.spec file to build properly under COPR, see https://copr.fedoraproject.org/coprs/portante/rsyslog-v8.15/, and so I hope to get that pushed into the various Fedora releases.

I have not tried to build this .spec file under Fedora COPR, as it will require special builds for various components which I don't quite follow yet why they are needed.

**Comment by rgerhards** [comment]
@alorbach @friedl could you please have a look?

**Comment by rgerhards** [comment]
@friedl we really should finally move forward with this. I guess kafaka is a bit different now... I'd appreciate if we could get this or a similar solution merged early next week, so that the next release does include it. I have assigned a release goal and would really like if we could met it.

**Comment by rgerhards** [comment]
@friedl can you comment on this PR?

**Comment by rgerhards** [comment]
@portante sorry, this looks like @friedl didn't really care... I have begun to work on the backlog in this respository. I think, though, that the "current" request can be closed. Most importantly, we now provide Fedora packages on SuSe OBS at

https://software.opensuse.org//download.html?project=home%3Argerhards&package=rsyslog

Spec files and everything else can be found here:

https://build.opensuse.org/project/show/home:rgerhards

Note that this is a different repository. That's the one the rsyslog project moved towards as a primary package source. I intend to sooner or later retire this repository here.

**Pull request closed without merging**
