### PR TITLE
add missing builddeps for epel7, correct define for PidFile

### PR DESCRIPTION
**Pull request by arrjay**
current rsyslog packages on epel7 (at least) do not correctly restart rsyslogd when logrotate takes place. this fixes that.

### CODE REVIEW

**Comment by arrjay** [comment]
fixes #25

**Comment by schlitzered** [comment]
could someone please review this?

**Comment by rgerhards** [comment]
@friedl @alorbach could you please have a look here? To me, the patch looks fine, but I am not deep enough into package build.

**Comment by arrjay** [comment]
I can answer any questions about this if needed, as well.

**Comment by friedl** [comment]
Sorry for having this unanswered for so long. Is this fix still needed?

**Comment by schlitzered** [comment]
as far as i know, yes. the logrotate config is still bropken

**Pull request merged**
